services:
  # Web Service for the Node.js backend
  - type: web
    name: board-game-tracker-api
    env: node
    plan: starter
    region: oregon
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: MONGO_URI
        fromDatabase:
          name: board-game-db
          property: connectionString

  # Static Site for React frontend
  - type: web
    name: board-game-tracker-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: board-game-tracker-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL

# Database Service
databases:
  - name: board-game-db
    plan: starter
    type: mongodb